#--font--
font_family JetBrains Mono
font_size 12

background_opacity 0.60

remeber_window_size no
initial_window_width 200c
initial_window_height 55c

dynamic_background_opacity yes

window_padding_width 4

hide_window_decorations yes
enable_audio_bell no
confrim_os_windows_close 0

cursor_shape_block


# BEGIN_KITTY_THEME
# 1984 Dark
include current-theme.conf
# END_KITTY_THEME